//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IDobj,129;DateUpdate,66;Flats,43;Series,75;SqALL,35;SqHome,45;SqKitch,30;Raspol,31;Flour,45;Flours,43;Material,44;Balcony,31;WC,44;Phone,46;New,43;Privat,44;IDcity,59;Rayon,115;Street,100;Price,43;PriceMeter,48;Object,44;Electricity,45;Hot,47;Water,47;Entrance,47;Security,46;Parking,44;Prava,44;SqLand,44;Live,45;")]
        public string GridColumnsWidth {
            get {
                return ((string)(this["GridColumnsWidth"]));
            }
            set {
                this["GridColumnsWidth"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root;database=realtor")]
        public string realtorConnectionString {
            get {
                return ((string)(this["realtorConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebServer")]
        public global::Realtor.ServicesLocation ServicesLocation {
            get {
                return ((global::Realtor.ServicesLocation)(this["ServicesLocation"]));
            }
            set {
                this["ServicesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.realty.loc/webservice")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
            set {
                this["BaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Activated {
            get {
                return ((bool)(this["Activated"]));
            }
            set {
                this["Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IDobj,133,0;DateUpdate,96,1;Flats,23,1;Series,75,1;SqALL,31,1;SqHome,31,1;SqKitch,30,1;Raspol,31,1;Flour,23,1;Flours,23,1;Material,32,1;Balcony,31,1;WC,30,1;Phone,23,1;New,23,1;Privat,23,1;IDcity,90,0;Rayon,92,1;Street,100,1;Price,49,1;PriceMeter,48,0;Object,55,0;Electricity,45,0;Hot,47,0;Water,47,0;Entrance,47,0;Security,46,0;Parking,44,0;Prava,23,0;SqLand,29,0;Live,23,0;Mebel,23,0;Term,31,0;")]
        public string GridColumns1 {
            get {
                return ((string)(this["GridColumns1"]));
            }
            set {
                this["GridColumns1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IDobj,133,0;DateUpdate,96,1;Flats,23,1;Series,75,1;SqALL,38,1;SqHome,27,1;SqKitch,23,1;Raspol,31,0;Flour,23,1;Flours,23,1;Material,32,1;Balcony,47,1;WC,30,1;Phone,23,1;New,23,1;Privat,23,1;IDcity,90,0;Rayon,115,1;Street,100,1;Price,51,1;PriceMeter,48,0;Object,55,0;Electricity,45,0;Hot,47,0;Water,47,0;Entrance,47,0;Security,46,0;Parking,44,0;Prava,83,1;SqLand,29,1;Live,23,1;Mebel,23,0;Term,31,0;")]
        public string GridColumns2 {
            get {
                return ((string)(this["GridColumns2"]));
            }
            set {
                this["GridColumns2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IDobj,133,0;DateUpdate,96,1;Flats,23,1;Series,75,1;SqALL,31,1;SqHome,27,1;SqKitch,23,1;Raspol,31,0;Flour,23,1;Flours,23,1;Material,32,1;Balcony,47,1;WC,30,1;Phone,23,1;New,23,1;Privat,23,1;IDcity,90,0;Rayon,115,1;Street,100,1;Price,55,1;PriceMeter,48,1;Object,55,0;Electricity,45,0;Hot,47,0;Water,47,0;Entrance,47,0;Security,46,0;Parking,44,0;Prava,129,1;SqLand,50,1;Live,23,1;Mebel,23,0;Term,31,0;")]
        public string GridColumns3 {
            get {
                return ((string)(this["GridColumns3"]));
            }
            set {
                this["GridColumns3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IDobj,133,0;DateUpdate,96,1;Flats,23,1;Series,75,1;SqALL,42,1;SqHome,27,1;SqKitch,23,1;Raspol,31,1;Flour,23,1;Flours,23,1;Material,32,1;Balcony,47,1;WC,30,1;Phone,23,1;New,23,1;Privat,23,1;IDcity,90,0;Rayon,115,1;Street,100,1;Price,48,1;PriceMeter,48,1;Object,113,1;Electricity,45,0;Hot,47,0;Water,47,0;Entrance,47,0;Security,46,0;Parking,44,0;Prava,81,1;SqLand,29,1;Live,23,0;Mebel,23,0;Term,31,0;")]
        public string GridColumns4 {
            get {
                return ((string)(this["GridColumns4"]));
            }
            set {
                this["GridColumns4"] = value;
            }
        }
    }
}
